### ISSUE TITLE
feature request: add keyword trigger

### ISSUE THREAD

**Issue by Siamkkas** [perzeuss/dify-discord-starter#5]
Currently, it's working well but it still has limited features that could enhance its effectiveness. I have a suggestion for improvement:

- The bot should be able to listen to all messages and respond individually (if the server owner requires).
- It should also listen for specific trigger words/phrase and REPLY only to messages that contain these triggers.

When the bot replies, it must REPLY directly to the specific message with the trigger word, rather than sending a general message.

**Comment by perzeuss** [comment]
Hi @Siamkkas,

thanks for the suggestion.
I wanted to have this for a private bot too, so I implemented it.
I've added this functionality with #6. You can test it on this branch `feat/5-add-keyword-trigger`. Let me know if it works for you.

However, you can only enable this feature globally for all servers. If you want settings per server, you would have to implement a database for it.
